import type { Metadata } from "next"
import "./globals.css"
import NavBar from "@/components/NavBar/NavBar"
import { ThemeProvider } from "@/components/theme-provider"
import VisitLog from "@/components/VisitLog/VisitLog"
export const metadata: Metadata = {
  title: "余心知秋的博客",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <>
      <html lang="en" suppressHydrationWarning style={{ scrollbarWidth: "none" }}>
        <head />
        <body>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <NavBar />
            {children}
            <VisitLog></VisitLog>
          </ThemeProvider>
        </body>
      </html>
    </>
  )
}
