import type { Metadata } from "next"
import "./globals.css"
import { ThemeProvider } from "@/components/my-ui/ThemeProvider"
import VisitLog from "@/components/business/VisitLog"
import { Toaster } from "@/components/ui/sonner"
import { SidebarProvider } from "@/components/ui/sidebar"
import { cookies } from "next/headers"
export const metadata: Metadata = {
  title: "余心知秋的博客",
  description: "Generated by create next app",
}

export default async function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  const cookieStore = await cookies()
  const defaultOpen = cookieStore.get("sidebar_state")?.value === "true"
  return (
    <>
      <html lang="en" suppressHydrationWarning style={{ scrollbarWidth: "none" }}>
        <head />
        <body>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <SidebarProvider defaultOpen={defaultOpen}>
              {children}
            </SidebarProvider>
            <VisitLog></VisitLog>
            <Toaster />
          </ThemeProvider>
        </body>
      </html>
    </>
  )
}
