import fp from 'fastify-plugin'
// import { ObjectId } from 'mongodb'

export default fp(async (fastify) => {
    const db = fastify.mongo.db()

    // 1. Init User (admin)
    const userCol = db.collection('user')
    if (await userCol.countDocuments() === 0) {
        await userCol.insertOne({
            username: 'admin',
            password: 'password', // Default password
            email: 'admin@example.com',
            role: 'owner', // Must be owner for full access
            avatar: '/user.png',
            createdAt: new Date()
        })
        fastify.log.info('Default user initialized: admin / password')
    }

    // 2. Init Article (Welcome post)
    const articleCol = db.collection('article')
    if (await articleCol.countDocuments() === 0) {
        // Need user ID
        const admin = await userCol.findOne({ username: 'admin' })
        if (admin) {
            await articleCol.insertOne({
                head: 'Welcome to My Blog',
                digest: 'This is a sample article generated by system initialization.',
                article: '# Welcome\n\nThis is your first article. You can edit or delete it via the dashboard.',
                cover: 'https://images.unsplash.com/photo-1499750310159-5b5f226932b7',
                user_id: admin._id,
                tag: [],
                time: new Date(),
                visit: 0
            })
            fastify.log.info('Default article initialized')
        }
    }

    // 3. Init Address (Personal Info)
    const addressCol = db.collection('address')
    if (await addressCol.countDocuments() === 0) {
        await addressCol.insertOne({
            email: 'admin@example.com',
            github: 'https://github.com',
            juejin: 'https://juejin.cn',
            qq: '123456789',
            wx: 'wx_id',
            bilibili: 'https://bilibili.com'
        })
        fastify.log.info('Default address initialized')
    }

    // 4. Init Saying (One quote)
    const sayingCol = db.collection('saying')
    if (await sayingCol.countDocuments() === 0) {
        await sayingCol.insertOne({
            content: 'Stay hungry, stay foolish.',
            author: 'Steve Jobs',
            time: new Date()
        })
        fastify.log.info('Default saying initialized')
    }
}, {
    name: 'db-init',
    decorators: {
        fastify: ['mongo']
    }
})
